#!/usr/bin/env python
from knowledge_representation import LongTermMemoryConduit

ltmc = LongTermMemoryConduit("127.0.0.1", 33060, "root", "", "villa_krr")
coke = ltmc.add_entity()
assert ltmc.entity_exists(coke)

nsb_concept = ltmc.get_concept("never seen before")

ltmc.get_entities_with_attribute_of_value("is_a", nsb_concept)

print("Done!")