#!/bin/bash

## Download saved bag files under the current directory.

if [ "$#" -gt "1" -o "$1" = "-h" ]
then    echo "usage: `basename $0` [option]"
        echo ""
        echo "Downloads saved bad files under the current directory from the"
        echo "main BWI server."
        exit 1
fi

RSYNC=/usr/bin/rsync
SERVER=nixons-head.csres.utexas.edu
TARGET_DIR=~bwilab/robot

exec $RSYNC -avz -e 'ssh -p40' $SERVER:$TARGET_DIR .
