#! /usr/bin/env python

# enable some python3 compatibility options:
from __future__ import absolute_import, print_function

import datetime
import sys
from bwi_logging.bagfile import distance_traveled

if __name__ == '__main__':

    if len(sys.argv) < 2:
        print('error: no bag files named\n', file=sys.stderr)
        print('usage: rosrun bwi_logging distance_traveled bag [bag2 ...]',
              file=sys.stderr)
        sys.exit(9)

    for filename in sys.argv[1:]:

        if not filename.endswith('.bag'):
            continue

        t, d, f = distance_traveled(filename)
        print('  time: ' + str(datetime.timedelta(seconds=t)) +
              '  distance: ' + "{0:.2f}".format(d) +
              '  filename: ' + f)

    sys.exit(0)
