#!/bin/bash

## Upload saved bag files from the current directory.

if [ "$#" -gt "1" -o "$1" = "-h" ]
then    echo "usage: `basename $0` [option]"
        echo ""
        echo "Uploads files matching 'bwi_*.bag' from the current directory to the"
        echo "main BWI server. \$HOSTNAME should be the lowest-level domain name."
        echo ""
        echo "Supports at most one of these options:"
        echo -e "\t-d\tdelete files uploaded successfully (default)"
        echo -e "\t-h\tprint this help message"
        echo -e "\t-k\tkeep uploaded files"
        exit 1
fi
del_opt=${1:-"-d"}
if [ "$del_opt" = "-d" ]
then    del_opt="--remove-sent-files"
else
        if [ "$del_opt" = "-k" ]
        then    del_opt=""
        else    echo "invalid parameter: $del_opt (try -h for help)"
                exit 2
        fi
fi

if [ "$HOSTNAME" == "" ]
then    echo '$HOSTNAME must be set for this operation'
        exit 9
fi

# See if there is anything to do.
if ! ls bwi_*.bag 1> /dev/null 2>&1
then    echo "No new bag files here to upload."
        exit 0
fi

# Make a subdirectory for the compressed files.
COMPRESSED="compressed"
mkdir -p $COMPRESSED

# Compress the data, then remove the uncompressed copies.
rosbag compress --output-dir=$COMPRESSED bwi_*.bag
rm -f bwi_*.bag

RSYNC=/usr/bin/rsync
SERVER=nixons-head.csres.utexas.edu
TARGET_DIR=~bwilab/robot/$HOSTNAME

# Make sure the target directory exists:
ssh -p40 $SERVER mkdir -p $TARGET_DIR

# Copy compressed files to the server
cd $COMPRESSED
echo $RSYNC -avz $del_opt -e 'ssh -p40' bwi_*.bag $SERVER:$TARGET_DIR
exec $RSYNC -avz $del_opt -e 'ssh -p40' bwi_*.bag $SERVER:$TARGET_DIR
