#!/usr/bin/env python

import sys
import yaml

with open(sys.argv[1],'r') as infile:
    doors = yaml.load(infile)

xdiff = float(sys.argv[2])
ydiff = float(sys.argv[3])

for door in doors:

    # xdiff
    door['approach'][0]['point'][0] += xdiff
    door['approach'][1]['point'][0] += xdiff
    door['door_corner_pt_1'][0] += xdiff
    door['door_corner_pt_2'][0] += xdiff

    # ydiff
    door['approach'][0]['point'][1] += ydiff
    door['approach'][1]['point'][1] += ydiff
    door['door_corner_pt_1'][1] += ydiff
    door['door_corner_pt_2'][1] += ydiff

with open('out.yaml','w') as outfile:
    outfile.write(yaml.dump(doors))

print "File with translated entities written out as out.yaml"
