#!/bin/bash -e 

rostopic pub --once /camera_pan_cmd std_msgs/Float32 -- -1.0
rostopic pub --once /camera_pan_tilt std_msgs/Float32 -- -0.2
sleep 5

rostopic pub --once /camera_pan_cmd std_msgs/Float32 -- -1.0
rostopic pub --once /camera_pan_tilt std_msgs/Float32 -- 0.2
sleep 1

rostopic pub --once /camera_pan_cmd std_msgs/Float32 -- 1.0
rostopic pub --once /camera_pan_tilt std_msgs/Float32 -- 0.2
sleep 5

rostopic pub --once /camera_pan_cmd std_msgs/Float32 -- 1.0
rostopic pub --once /camera_pan_tilt std_msgs/Float32 -- -0.2
sleep 1

