#!/usr/bin/env python

# This code is based on code available at the following location: 
# https://www.assembla.com/code/XD_DSbot/subversion/nodes/trunk/Info/Simu/PololuMaestro.py?rev=405
# The original code is unlicensed, and has been re-packaged as BSD in this 
# code-release. Please contact the package distributors in case of licensing
# discrepancies
#
# Copyright (C) 2014, The XD_DSbot Dev Team, Jack O'Quin, Piyush Khandelwal
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
#  * Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#  * Redistributions in binary form must reproduce the above
#    copyright notice, this list of conditions and the following
#    disclaimer in the documentation and/or other materials provided
#    with the distribution.
#  * Neither the name of the author nor of other contributors may be
#    used to endorse or promote products derived from this software
#    without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
# FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
# COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
# BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
# ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

"""
This is a ROS device driver node that interacts with a Polulu Maestro Servo
Controller. It has been tested on the Polulu Micro MaestroDevice, but should
also work with the Polulu Mini MaestroDevice 12, 18 and 24.

.. note::

   TODO: add diagnositics

"""

import math
import rospy
import select
import serial
import sys
import threading
import time

from std_msgs.msg import Float32

HS422_MIN_TICK = 2080
HS422_MAX_TICK = 9920
min_tick = HS422_MIN_TICK
max_tick = HS422_MAX_TICK

def radians_to_ticks(rads):
    return (min_tick + max_tick) / 2 + \
           int((rads / math.pi) * (max_tick - min_tick)) 

def ticks_to_radians(ticks):
    return (ticks - (min_tick + max_tick) / 2) * \
            math.pi / (max_tick - min_tick)

class MaestroDevice:
    """ Class for managing the Polulu Maestro Servo Controller """

    def __init__(self, port='/dev/ttyACM0', baud=9600):
        self.port = port
        """ Path name for Arduino serial port. """
        self.baud = baud
        """ Baud rate for Arduino serial port. """
        self.dev = None
        """ Arduino serial device connection. """
        self.lock = threading.Lock()

    def close(self):
        if self.dev:
            self.dev.close()
        self.dev = None

    def ok(self):
        """ :returns: ``True`` if Arduino contacted. """
        return self.dev is not None

    def open(self):
        """ Open the Maestro serial device interface.

        :returns: ``True`` if open succeeds.
        """
        try:
            self.dev = serial.Serial(self.port, self.baud)
            # give a little time to the MaestroDevice to breeze 
            time.sleep(0.25)
        except IOError as e:
            # HACK: serial does not return errno.ENOTTY as it should,
            #       so check the exact string.
            enotty = ("Could not configure port: "
                      + "(25, 'Inappropriate ioctl for device')")
            if str(e) != enotty:        # is it a serial port?
                rospy.logerr('Serial port open failed at '
                             + str(self.baud) + ' baud: ' + str(e))
                return False
            else:
                rospy.logerr('Serial port is not configured as tty ' +
                             '(errno.ENOTTY): ' + str(e))
                return False
        else:
            rospy.loginfo('Serial port ' + self.port + ' opened at '
                          + str(self.baud) + ' baud.')
            self.dev.flushInput()       # discard any old data
            return True

    def __read(self):
        """ Reads one byte of data from the serial device 

        :returns: read byte
        """
        if not self.ok():
            rospy.logdebug('Tried to read from a closed device')
            return ' '
        try:
            readbyte = self.dev.read()
            return readbyte
        except serial.SerialException as e:
            rospy.logerr('Serial port ' + self.port +
                         ' read failed: ' + str(e))
            self.close()
        except (select.error, OSError) as e:
            errno_, perror = e.args
            rospy.logwarn('Serial port read error: ' + str(perror))
            self.close()
        return ' '

    def __write(self, data):
        """ Writes specified data to file """
        if not self.ok():
            rospy.logdebug('Tried to write to a closed device')
            return 0
        try:
            self.dev.write(data)
        except serial.SerialException as e:
            rospy.logerr('Serial port ' + self.port +
                         ' write failed: ' + str(e))
            self.close()
        except (select.error, OSError) as e:
            errno_, perror = e.args
            rospy.logwarn('Serial port write error: ' + str(perror))
            self.close()
  
    def __send_header(self, cmd, device):
        """ Sends the header of the command, depending ont the protocol """
        if  (device & 0x80) == 0 :              #Pololu protocol
            self.__write(chr(0xAA))           #start byte
            self.__write(chr(device & 0x7f))  #device
            cmd &= 0x7f                         #in this mode, the MSB of the 
        self.__write(chr(cmd))                #command is cleared

    def __send_command(self, cmd, device):
        """ Sends a command without data """
        self.__send_header(cmd, device)

    def __send_command_b(self, cmd, byte_arg, device):
        """ Sends a command with 1 byte of data """
        self.__send_header(cmd, device)
        self.__write(chr(byte_arg & 0x7f))

    def __send_command_bi(self, cmd, byte_arg, int_arg, device):
        """ sends a command with 3 byte of data """
        self.__send_header(cmd, device) 
        self.__write(chr(byte_arg & 0x7f))
        self.__write(chr(int_arg & 0x7f))        #data lower 7 bits
        self.__write(chr((int_arg >> 7) & 0x7f)) #data bits 7-13

    def __send_command_ii(self, cmd, int_arg1, int_arg2, device):
        """ sends a command with 4 bytes of data """
        self.__send_header(cmd, device) 
        self.__write(chr(int_arg1 & 0x7f))        #data lower 7 bits
        self.__write(chr((int_arg1 >> 7) & 0x7f)) #data bits 7-13
        self.__write(chr(int_arg2 & 0x7f))        #data lower 7 bits
        self.__write(chr((int_arg2 >> 7) & 0x7f)) #data bits 7-13

    def __send_command_var_i(self, cmd, byte_arg, int_values, device):
        """ Sends a command with variable bytes of data """
        self.__send_header(cmd, device)
        self.__write(chr(len(int_values)))     #number of int values
        self.__write(chr(byte_arg & 0x7f))     
        for i in int_values:
            self.__write(chr(i & 0x7f))        #data lower 7 bits
            self.__write(chr((i >> 7) & 0x7f)) #data bits 7-13

    def __receive_int(self):
        """ Receives 2 bytes of data """
        low  = self.__read()
        high = self.__read()
        return int(ord(low) | (ord(high) << 8))

    def __receive_byte(self):
        """ Receives 1 byte of data """
        return ord(self.__read())

    def set_target(self, servo, angle, device=0x80):
        """ Set the target for a servo
        :param servo: is the servo number (typically 0-23)
        :param angle: is the target, from 256 to 13120, in quarter-microseconds
                      (center=6000, off=0)
        :param device: is the id of the MaestroDevice device (0-127, default on
                       boards is 12, all device if not set)
        """
        self.lock.acquire()
        self.__send_command_bi(0x84, servo, angle, device)
        self.lock.release()

    def set_target_minissc(self,servo, angle):
        """ Set the target using the Mini-SSC protocol
        :param servo: is the sum of the servo number (typically 0-23) and the
                      servo offset of the device
        :param angle: is the target, from 0 to 254, mapped between
                      neutral-range and neutral+range. 127 is neutral.
        """
        self.lock.acquire()
        self.__write("\xFF"+chr(servo)+chr(angle))
        self.lock.release()

    def set_multiple_targets(self, first_servo, angles, device=0x80):
        """ Set simultaneously targets for a contiguous block of servos (Mini
        MaestroDevice 12, 18 and 24 only)
        :param first_servo: is the lower servo number in the block 
                            (typically 0-23)
        :param angles: is the list of targets, each from 256 to 13120, in
                       quarter-microseconds (center=6000, off=0)
        :param device: is the id of the MaestroDevice device (0-127, default on
                       boards is 12, all device if not set)
        """
        self.lock.acquire()
        self.__send_command_var_i(0x9F, first_servo, angles, device)
        self.lock.release()

    def set_speed(self, servo, speed, device=0x80):
        """ Set the speed for a servo
        :param servo: is the servo number (typically 0-23)
        :param speed: is the servo speed (0=full, 1=slower), in 
                      (0.25 us)/(10 ms) when T=20ms. 
                      see http://www.pololu.com/docs/0J40/4.e for details
        :param device: is the id of the MaestroDevice device (0-127, default on
                       boards is 12, all device if not set)
        """
        self.lock.acquire()
        self.__send_command_bi(0x87, servo, speed, device)
        self.lock.release()

    def set_acceleration(self, servo, acceleration, device=0x80):
        """ Set the acceleration for a servo
        :param servo: is the servo number (typically 0-23)
        :param acceleration: is servo acceleration (0=full, 1=slower), 
                             in (0.25 us)/(10 ms)/(80 ms) when T=20ms. 
                             see http://www.pololu.com/docs/0J40/4.e for details
        :param device: is the id of the MaestroDevice device (0-127, default on
                       boards is 12, all device if not set)
        """
        self.lock.acquire()
        self.__send_command_bi(0x89, servo, acceleration, device)
        self.lock.release()

    def set_pwm(self, on_time, period, device=0x80):
        """ Set the pwm output of a channel (Mini MaestroDevice 12, 18 and 24
        only)
        :param on_time: is the part of the period the output will be high 
                        (unit : 1/48 us)
        :param period: is the total period length (unit : 1/48 us)
                       see http://www.pololu.com/docs/0J40/4.a for details
        """
        self.lock.acquire()
        self.__send_command_ii(0x8A, on_time, period, device)
        self.lock.release()

    def go_home(self, device=0x80):
        """ Set all servos to their home position. Servos set to "ignore" will
        remain unchanged, servos set to "off" will turn off.
        :param servo: is the servo number (typically 0-23)
        :param device: is the id of the MaestroDevice device (0-127, default on
                       boards is 12, all device if not set)
        """
        self.lock.acquire()
        self.__send_command(0xA2, device)
        self.lock.release()

    def get_position(self, servo, device=0x80):
        """ Gets the current position of a servo
        :param device: is the id of the MaestroDevice device (0-127, default on
                       boards is 12, all device if not set)
        """
        self.lock.acquire()
        self.__send_command_b(0x90, servo, device)
        val = self.__receive_int()
        self.lock.release()
        return val

    def get_moving_state(self, device=0x80):
        """ Checks if some servos are moving
        :param device: is the id of the MaestroDevice device (0-127, default on
                       boards is 12, all device if not set)
        """
        self.lock.acquire()
        self.__send_command(0x93, device)
        val =  self.__receive_byte()
        self.lock.release()
        return val

    def get_errors(self, device=0x80):
        """ Gets the current error flags
        :param device: is the id of the MaestroDevice device (0-127, default on
                       boards is 12, all device if not set)
        """
        self.lock.acquire()
        self.__send_command(0xA1, device)
        val = self.__receive_int()
        self.lock.release()
        return val

class Servo(object):

    def __init__(self, maestro, servo_number, name=None, offset=None,
                min_angle=None, max_angle=None, speed=None):

        self.maestro = maestro
        self.servo_number = servo_number

        if name is None:
            name = 'servo' + str(servo_number)
        self.name = name
        cmd_name = name + '_cmd'
        status_name = name + '_status'
        self.cmd_sub = rospy.Subscriber(cmd_name, Float32,
                                        self.cmd_callback)
        self.status_pub = rospy.Publisher(status_name, Float32) 

        self.angle_offset = offset if offset is not None else 0
        self.min_angle = min_angle if min_angle is not None else -math.pi/2
        self.max_angle = max_angle if max_angle is not None else math.pi/2
        self.speed = speed if speed is not None else 4.0 #rad/s

        # Convert speed to ticks per 10 ms
        self.speed /= 100.0
        self.speed = int(self.speed * (max_tick - min_tick) / math.pi)

    def publish(self):
        ticks = self.maestro.get_position(self.servo_number)
        angle = ticks_to_radians(ticks) - self.angle_offset
        self.status_pub.publish(angle)

    def cmd_callback(self, msg):
        # rospy.loginfo('Setting servo ' + self.name + '(servo ' +
        #               str(self.servo_number) + ') to ' + str(msg.data) + 
        #               ' radians.')
        angle = msg.data + self.angle_offset
        if angle < self.min_angle or angle > self.max_angle:
            rospy.logerr('Angle outside servo range. Moving servo to max value')
            angle = max(angle, self.min_angle)
            angle = min(angle, self.max_angle)
        ticks = radians_to_ticks(angle)
        # rospy.loginfo('  Setting servo ' + self.name + '(servo ' +
        #               str(self.servo_number) + ') to ' + str(ticks) + 
        #               ' ticks.')
        # Slow down servo for now
        self.maestro.set_speed(self.servo_number, self.speed)
        self.maestro.set_target(self.servo_number, ticks)

    def shutdown(self):
        self.cmd_sub.unregister()
        self.status_pub.unregister()

class PololuDriver(object):

    def __init__(self, port='/dev/polulu_servo_serial', baud=9600):

        rospy.init_node('pololu_driver')
        rospy.on_shutdown(self.shutdown)

        port = rospy.get_param('~port', port)
        baud = rospy.get_param('~baud', baud)
        self.maestro = MaestroDevice(port, baud)

        # Get servo configuration
        min_tick = rospy.get_param('~min_tick', HS422_MIN_TICK)
        max_tick = rospy.get_param('~max_tick', HS422_MAX_TICK)
        global_min_angle = rospy.get_param('~min_angle', None)
        global_max_angle = rospy.get_param('~min_angle', None)
        global_speed = rospy.get_param('~speed', None)

        num_servos = rospy.get_param('~num_servos', 1)
        servos = rospy.get_param('~servos', None)

        self.servos = []
        if servos is not None: 
            for servo in servos:
                if 'number' not in servo:
                    rospy.logfatal('A servo in ~servos does not specify number')
                    sys.exit(-1)
                name = servo['name'] if 'name' in servo else None
                offset = servo['offset'] if 'offset' in servo else None
                min_angle = servo['min_angle'] if 'min_angle' in servo \
                                               else global_min_angle
                max_angle = servo['max_angle'] if 'max_angle' in servo \
                                               else global_max_angle
                speed = servo['speed'] if 'speed' in servo else global_speed
                self.servos.insert(Servo(self.maestro, servo['number'], name,
                                         offset, min_angle, max_angle, speed))
        else:
            self.servos = [Servo(self.maestro, i, 
                                 min_angle=global_min_angle,
                                 max_angle=global_max_angle,
                                 speed=global_speed) 
                           for i in range(num_servos)]

        self.spin()

    def shutdown(self):
        """ Called by rospy on shutdown. """
        for servo in self.servos:
            servo.shutdown()
        self.maestro.close()

    def run(self):
        rospy.spin()

    def spin(self):
        """ Main driver loop. """
        slow_poll = rospy.Rate(0.25)    # slow poll frequency
        fast_loop = rospy.Rate(50)
        while not rospy.is_shutdown():
            if self.maestro.ok():       # device connected?
                for servo in self.servos:
                    servo.publish()
            elif self.maestro.open():   # open succeeded?
                pass
            else:
                rospy.logwarn('Device not connected!')
                slow_poll.sleep()
            fast_loop.sleep()

if __name__ == '__main__':
    node = PololuDriver()
